# 创建触发器
createTriggers: 
  - 创建谁是卧底
# 加入触发器
joinTriggers: 
  - 加入
  - 加入谁是卧底
# 当前玩家触发器
showTriggers: 
  - 当前玩家
  - 玩家列表
# 切换模式触发器
modeTriggers: 
  - 模式
  - 切换模式
# 开始触发器
startTriggers: 
  - 开
  - 开始
  - go
# 描述结束触发器
nextTriggers: 
  - 结束
# 投票触发器
voteTriggers: 
  - 投票
  - vote
  - 投
# 强制结束触发器
stopTriggers: 
  - 结束谁是卧底
# 规则触发器
ruleTriggers: 
  - 谁是卧底规则
# 创建消息
createMessage: "创建成功~\n请输入\"加入\"加入游戏！\n人数大于三人后可输入\"开始\"开始游戏！"
# 重复创建消息
alreadyCreateMessage: "游戏已存在！当前玩家{num}人，可\n请输入\"加入\"加入游戏！输入\"谁是卧底规则\"查看规则，\n人数大于三人后可输入\"开始\"开始游戏！"
# 加入消息
joinMessage: "加入成功~\n当前玩家{num}人"
# 重复加入消息
alreadyJoinMessage: "你已经加入过了！\n当前玩家{num}人"
# 游戏进行中消息
inGamingMessage: 游戏正在进行中！
# 当前玩家消息
showMessage: '当前玩家: {player_list}'
# 词条消息
wordMessage: '你的词条: {word}'
# 白板消息
whiteMessage: 你的词条——欸？！你没有词条呢，多观察一下他人的发言并模仿吧！
# 强制结束消息
stopMessage: 游戏已结束！
# 模式提醒消息
modeMessage: "默认为标准模式，可通过\"模式 1/2/3\"切换至其他模式\n1.标准模式: 仅有1个卧底\n2.多卧底模式: 适用于人较多的情况，四分之一玩家为卧底\n3.随机白板模式: 将随机一部分玩家为白板(不超过四分之一)"
# 切换模式消息
switchModeMessage: '已切换至{mode}！'
# 模式不存在消息
noModeMessage: 该模式不存在！
# 特殊模式消息
specialModeMessage: 游戏模式好像变得奇怪了！
# 卧底胜利消息
spyWinMessage: 游戏结束啦！卧底获得胜利！
# 卧底失败消息
spyLostMessage: 游戏结束啦！卧底输了！
# 特殊模式结束消息
specialModeEndMessage: 游戏结束啦！本轮没有玩家获胜，因为本轮为【特殊模式】，全部玩家都是白板！
# 不知道谁赢消息
normalEndMessage: "游戏结束啦！以下玩家获得胜利:\n{win_list}"
# 描述阶段消息
descriptionMessage: "描述阶段！请按照以下顺序轮流用一句话描述自己的词语（但不可以包含自己的词语），所有人均描述完毕后发送\"{nextTriggers}\"进入下一阶段。\n{player_list}"
# 投票消息
voteMessage: "投票阶段！请输入\"投票 编号\"进行投票，所有人均描述完毕后自动进入下一回合。\n0. 弃票\n{player_list}"
# 规则
rule: 标准模式下，每个玩家会拿到自己的词条，其中卧底的词条与其他人的不一样！每个玩家需要轮流描述自己的词，描述不能重复，若出现自己的词则直接判输。之后进行投票选出卧底。票数最多的玩家将会被淘汰。一直重复下去，直到卧底被淘汰或卧底的人数占剩余玩家总数大于等于三分之一。
# 强制进入特殊模式(不通知)的概率，可填0-100，对应0%-100%的概率，为0时就是禁用特殊模式 。特殊模式: 所有玩家均为白板，只剩下3名玩家时结束。该模式也可通过"切换模式 114514"进入。
specialModeOdds: 5