# 根据id获得图片及其数据 psid-87984524
getDetailOfId: 'psid-'
# 搜索图片 ptst-图片
picToSearch: 'ptst-'
# 排行榜 rank-daily-页码 可选daily|weekly|monthly|rookie|original|male|female|daily_r18|weekly_r18|male_r18|female_r18|r18g
showRank: 'rank-'
# 获取作者所有的插画 user-87915-页码
findUserWorksById: 'user-'
# 搜索番剧 ptsf-图片
searchInfoByPic: 'ptsf-'
# 涩图 setu 或者setu loli
setu: 来点色图
# Lolicon 详细看https://api.lolicon.app/#/setu?id=tag
lolicon: loli
# 搜索标签排行榜 tag-萝莉-页码
tag: 'tag-'
# 帮助
help: 帮助
# 晶格化命令
lowPoly: 晶格化
# 从指定库存发送图片
warehouse: 来点库存